function normalizeString(value) {
  return String(value || "").trim();
}

export const adminOnboardingTargetSelectors = {
  nav_regional_setup: '[data-onboarding="nav-regional-setup"]',
  regional_setup_form: '[data-onboarding="regional-setup-form"]',
  regional_setup_save: '[data-onboarding="regional-setup-save"]',
  branding_settings_card: '[data-onboarding="branding-settings-card"]',
  site_settings_card: '[data-onboarding="site-settings-card"]',
  page_settings_home_card: '[data-onboarding="page-settings-home-card"]',
  page_settings_testimonials_card: '[data-onboarding="page-settings-testimonials-card"]',
  site_settings_form: '[data-onboarding="site-settings-form"]',
  site_settings_save: '[data-onboarding="site-settings-save"]',
  branding_settings_form: '[data-onboarding="branding-settings-form"]',
  branding_settings_save: '[data-onboarding="branding-settings-save"]',
  homepage_section_tabs: '[data-onboarding="homepage-section-tabs"]',
  homepage_hero_panel: '[data-onboarding="homepage-hero-panel"]',
  homepage_hero_actions: '[data-onboarding="homepage-hero-actions"]',
  media_workspace: '[data-onboarding="media-workspace"]',
  media_add_assets_button: '[data-onboarding="media-add-assets-button"]',
  media_add_folder_button: '[data-onboarding="media-add-folder-button"]',
  media_details_panel: '[data-onboarding="media-details-panel"]',
  what_we_do_list: '[data-onboarding="what-we-do-list"]',
  testimonials_list: '[data-onboarding="testimonials-list"]',
  events_list: '[data-onboarding="events-list"]',
  events_create_button: '[data-onboarding="events-create-button"]',
  courses_list: '[data-onboarding="courses-list"]',
  courses_create_button: '[data-onboarding="courses-create-button"]',
  nav_site_settings: '[data-onboarding="nav-site-settings"]',
  nav_page_settings: '[data-onboarding="nav-page-settings"]',
  nav_media: '[data-onboarding="nav-media"]',
  account_package_panel: '[data-onboarding="account-package-panel"]',
  account_upgrade_growth_button: '[data-onboarding="account-upgrade-growth-button"]',
  account_custom_domain_card: '[data-onboarding="account-custom-domain-card"]',
  account_growth_domain_upgrade_panel: '[data-onboarding="account-growth-domain-upgrade-panel"]',
  account_domain_setup_panel: '[data-onboarding="account-domain-setup-panel"]',
  payments_setup_locked_root: '[data-onboarding="payments-setup-locked-root"]',
  payments_setup_locked_unlocks: '[data-onboarding="payments-setup-locked-unlocks"]',
  payments_setup_locked_action: '[data-onboarding="payments-setup-locked-action"]',
  payments_setup_hero_panel: '[data-onboarding="payments-setup-hero-panel"]',
  payments_setup_guidance_panel: '[data-onboarding="payments-setup-guidance-panel"]',
  payments_setup_action_button: '[data-onboarding="payments-setup-action-button"]',
  payments_setup_embed_panel: '[data-onboarding="payments-setup-embed-panel"]',
  membership_plans_create_button: '[data-onboarding="membership-plans-create-button"]',
  membership_plans_section: '[data-onboarding="membership-plans-section"]',
  membership_plans_list: '[data-onboarding="membership-plans-list"]',
  members_list_toolbar: '[data-onboarding="members-list-toolbar"]',
  members_list_records: '[data-onboarding="members-list-records"]',
  member_detail_summary: '[data-onboarding="member-detail-summary"]',
  member_detail_state: '[data-onboarding="member-detail-state"]',
  member_detail_membership: '[data-onboarding="member-detail-membership"]',
  payments_records_toolbar: '[data-onboarding="payments-records-toolbar"]',
  payments_records_list: '[data-onboarding="payments-records-list"]',
  admins_invite_button: '[data-onboarding="admins-invite-button"]',
  admins_active_list: '[data-onboarding="admins-active-list"]',
  admins_pending_list: '[data-onboarding="admins-pending-list"]',
};

export function resolveAdminOnboardingTargetSelector(targetKey) {
  return adminOnboardingTargetSelectors[normalizeString(targetKey)] || "";
}
