export const initialEditEventFormState = {
  error: "",
  success: "",
  upgradeNotice: null,
  values: {
    title: "",
    slug: "",
    summary: "",
    description: "",
    imageAssetId: "",
    imageAlt: "",
    location: "",
    startDate: "",
    endDate: "",
    startTime: "",
    endTime: "",
    capacity: "",
    pricingMode: "free",
    price: "",
    currency: "USD",
    externalPaymentUrl: "",
    paymentInstructions: "",
    refundWindowMode: "default",
    refundWindowHours: "48",
    refundPolicy: "full_refund_before_window",
    registrationEligibility: "members-only",
    bookingMode: "single_attendee",
    maxAttendeesPerBooking: "2",
    guestDetailsMode: "name_only",
    visibility: "public",
    allowWaitlist: "true",
    category: "",
    status: "draft",
  },
};
